export const input = {
  background: "#E7EDF3",
  border: "none",
  padding: "10px 35px 10px 35px",
  margin: "0px 0px 10px 0px",
  fontSize: "14px",
  fontFamily: "Roboto",
  lineHeight: "1px",
  boxShadow: "none",
  outline: "none",
  borderRadius: "5px",
  height: "auto",
  width: "auto",
};

export const buttonStyle = {
  border: {
    border: "1px solid #5E35B1",
    background: "var(--white)",
    color: "var(--primary)",
    borderRadius: "50px",
    padding: "5px 14px",
    font: "-webkit-control",
    outline: "none",
    height: "auto",
    width: "auto",
    textTransform: "none",
    letterSpacing: "normal",
    lineHeight: "normal",
    fontFamily: "Roboto",
  },
  fill: {
    background: "#713DDA",
    boxShadow: "0px 4px 19px rgba(0, 0, 0, 0.1)",
    borderRadius: "50px",
    border: "none",
    color: "var(--white)",
    width: "247px",
    height: "38px",
    marginTop: "11px",
    fontSize: "18px",
    outline: "none",
    textTransform: "none",
    letterSpacing: "normal",
    lineHeight: "normal",
    fontFamily: "Roboto",
  },
  transparent: {
    background: "transparent",
    color: "var(--primary)",
    border: "none",
    outline: "none",
    height: "auto",
    width: "auto",
    textTransform: "none",
    letterSpacing: "normal",
    fontSize: "14px",
    lineHeight: "normal",
    fontFamily: "Roboto",
    padding: "0px 0px 0px 10px",
    fontWeight: "400",
  },
};
